name: Build env action for github

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    # build env
    - run: conda env create -f environment.yml
      shell: bash
    # install flake8
    - run: |
        source ${CONDA}/bin/activate JackFramework-torch1.7.1
        conda install flake8
        lake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash
    # install the lib
    - run: |
        source ${CONDA}/bin/activate JackFramework-torch1.7.1
        sh install.sh
      shell: bash
    # test the JackFramework
    - run: |
        source ${CONDA}/bin/activate JackFramework-torch1.7.1
        python -c "import JackFramework as jf; print(jf.version())"
      shell: bash
